# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes mean density for each occasion
#'
#' @param D density parameter 
#' @param J total number of occasions
#' @param pr0 initial distribution over life states
#' @param tpms list of transition probability matrices (one per occasion)
#'
#' @return  vector with j^th entry the mean density on occasion j 
#'
C_calc_D <- function(D, J, pr0, tpms) {
    .Call(`openpopscr_C_calc_D`, D, J, pr0, tpms)
}

#' Computes log-likelihood of Jolly-Seber model 
#'
#' @param n number of individuals 
#' @param J total number of occasions 
#' @param M total number of mesh points
#' @param pr0 initial distribution over life states
#' @param pr_capture output of calc_pr_capture() in JsModel
#' @param tpms output of calc_tpms() in JsModel
#' @param num_cores number of processor cores to use in parallelisation 
#' @param num_states 2 = CJS model, 3 = JS model 
#'
#' @return log-likelihood value 
#' 
C_calc_llk <- function(n, J, M, pr0, pr_capture, tpms, num_cores, num_states) {
    .Call(`openpopscr_C_calc_llk`, n, J, M, pr0, pr_capture, tpms, num_cores, num_states)
}

#' Computes detection probability (seen at least once) for Jolly-Seber model 
#'
#' @param J total number of occasions 
#' @param pr0 initial distribution over life states
#' @param pr_captures list of empty capture histories, see calc_pdet() in JsModel
#' @param tpms output of calc_tpms() in JsModel
#'
#' @return pdet = probability seen at some time on the survey 
#' 
C_calc_pdet <- function(J, pr0, pr_captures, tpms) {
    .Call(`openpopscr_C_calc_pdet`, J, pr0, pr_captures, tpms)
}

#' Computes probability of each capture record for Jolly-Seber model 
#'
#' @param n number of individuals 
#' @param J total number of occasions 
#' @param K total number of traps ever used  
#' @param M total number of mesh points
#' @param capvec a pointer to the capthist array 
#' @param enc_rate a pointer to the encounter rate array, see calc_pr_capture() in JsModel
#' @param usage matrix with J x K where (j,k) entry is usage of trap k in occasion j
#' @param num_cores number of processor cores to use in parallelisation 
#' @param num_states: 2 = CJS model, 3 = JS model 
#'
#' @return  Array with (i,j,m) entry the probability of capture record for individual i in occasion j given activity centre at mesh point m  
#' 
C_calc_pr_capture <- function(n, J, K, M, capvec, enc_rate, usage, num_cores, num_states) {
    .Call(`openpopscr_C_calc_pr_capture`, n, J, K, M, capvec, enc_rate, usage, num_cores, num_states)
}

