# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes mean density for each occasion
#'
#' @param D density parameter 
#' @param J total number of occasions
#' @param pr0 initial distribution over life states
#' @param tpms list of transition probability matrices (one per occasion)
#'
#' @return  vector with j^th entry the mean density on occasion j 
#'
C_calc_D <- function(D, J, pr0, tpms) {
    .Call(`_openpopscr_C_calc_D`, D, J, pr0, tpms)
}

#' Computes log-likelihood 
#'
#' @param n number of individuals 
#' @param J total number of occasions 
#' @param M total number of mesh points
#' @param pr0 initial distribution over life states
#' @param pr_capture output of calc_pr_capture() in JsModel
#' @param tpms output of calc_tpms() in JsModel
#' @param num_states 2 = CJS model, 3 = JS model 
#'
#' @return log-likelihood value 
#' 
C_calc_llk <- function(n, J, M, pr0, pr_capture, tpms, num_states, entry) {
    .Call(`_openpopscr_C_calc_llk`, n, J, M, pr0, pr_capture, tpms, num_states, entry)
}

#' Computes detection probability (seen at least once)  
#'
#' @param J total number of occasions 
#' @param pr0 initial distribution over life states
#' @param pr_captures list of empty capture histories, see calc_pdet() in JsModel
#' @param tpms output of calc_tpms() in JsModel
#'
#' @return pdet = probability seen at some time on the survey 
#' 
C_calc_pdet <- function(J, pr0, pr_captures, tpms, num_states) {
    .Call(`_openpopscr_C_calc_pdet`, J, pr0, pr_captures, tpms, num_states)
}

#' Computes log-likelihood of Jolly-Seber model 
#'
#' @param n number of individuals 
#' @param J total number of occasions 
#' @param M total number of mesh points
#' @param pr0 initial distribution over life states
#' @param pr_capture output of calc_pr_capture() in JsModel
#' @param tpms output of calc_tpms() in JsModel
#' @param num_states 2 = CJS model, 3 = JS model 
#'
#' @return log-likelihood value 
#' 
C_calc_move_llk <- function(n, J, pr0, pr_capture, tpms, num_cells, inside, dx, dt, sd, num_states, entry) {
    .Call(`_openpopscr_C_calc_move_llk`, n, J, pr0, pr_capture, tpms, num_cells, inside, dx, dt, sd, num_states, entry)
}

#' Computes detection probability (seen at least once) for Jolly-Seber model 
#'
#' @param J total number of occasions 
#' @param pr0 initial distribution over life states
#' @param pr_captures list of empty capture histories, see calc_pdet() in JsModel
#' @param tpms output of calc_tpms() in JsModel
#'
#' @return pdet = probability seen at some time on the survey 
#' 
C_calc_move_pdet <- function(J, pr0, pr_captures, tpms, num_cells, inside, dx, dt, sd, num_states) {
    .Call(`_openpopscr_C_calc_move_pdet`, J, pr0, pr_captures, tpms, num_cells, inside, dx, dt, sd, num_states)
}

#' Computes probability of each capture record
#'
#' @param n number of individuals 
#' @param J total number of occasions 
#' @param K total number of traps ever used  
#' @param M total number of mesh points
#' @param capvec a pointer to the capthist array 
#' @param enc_rate a pointer to the encounter rate array, see calc_pr_capture() in JsModel
#' @param usage matrix with J x K where (j,k) entry is usage of trap k in occasion j
#' @param num_states: 1 = SCR model, 2 = CJS model, 3 = JS model 
#' @param detector_type 1 = count, 2 = proximity/binary, 3 = multi-catch, 4 = transect 
#'
#' @return  Array with (i,j,m) entry the probability of capture record for individual i in occasion j given activity centre at mesh point m  
#' 
C_calc_pr_capture <- function(n, J, K, M, capthist, enc0, usage, num_states, detector_type, n_prim, S, entry) {
    .Call(`_openpopscr_C_calc_pr_capture`, n, J, K, M, capthist, enc0, usage, num_states, detector_type, n_prim, S, entry)
}

